NetzOptimize/pyQA

FUNCTIONS/helper.py

enter key function presses the ENTER key

added enter_key function

---

FUNCTIONS/helper.py

Added explicit functions variables

---

FUNCTIONS/helper.py

Added explicit -> title_is

---

FUNCTIONS/helper.py

🚀 Added explicit -> title_contains

---

FUNCTIONS/helper.py

🚀 Added explicit -> visibility_of_element_located

---

FUNCTIONS/helper.py

🚀 Added explicit -> visibility_of

---

FUNCTIONS/helper.py

🚀 Added explicit -> presence_of_all_elements_located

---

FUNCTIONS/helper.py

🚀 Added explicit -> text_to_be_present_in_element

---

FUNCTIONS/helper.py

🚀 Added explicit -> text_to_be_present_in_element_value

---

FUNCTIONS/helper.py

🚀 Added explicit -> frame_to_be_available_and_switch_to_it

---

FUNCTIONS/helper.py

🚀 Added explicit -> invisibility_of_element_located

---

FUNCTIONS/helper.py

🚀 Added explicit -> staleness_of

---

FUNCTIONS/helper.py

🚀 Added explicit -> element_to_be_selected

---

FUNCTIONS/helper.py

🚀 Added explicit -> element_selection_state_to_be

---

FUNCTIONS/helper.py

🚀 Added explicit -> element_located_selection_state_to_be

---

FUNCTIONS/helper.py

🚀 Added explicit -> alert_is_present

---

FUNCTIONS/helper.py

🚀 Added explicit -> title_is

---

FUNCTIONS/helper.py

🚀 Added explicit -> presence_of_element_located

---

FUNCTIONS/helper.py

🚀 Added explicit-> visibility_of_element_located

---

FUNCTIONS/helper.py

🚀 Added explicit -> for name and Link_text

---

FUNCTIONS/helper.py

🚀 Added explicit -> Partial_link_text

---

FUNCTIONS/helper.py

Support added for:
- input
- backspace
- enter key
- click

✅ individual functions can now be applied to element

---

FUNCTIONS/helper.py

Added  list to string conversation function

Added the list to the string conversion function.
